// client_angular/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import '../node_modules/bootstrap/dist/css/bootstrap.min.css'

@Component({
    selector: 'my-app',
    templateUrl: 'app.component.html',
})
export class AppComponent {
    title = 'My New Vocabularies';
    constructor() {
    }

    ngOnInit() {
    }
}
<!--<ribbon-bar [tabs]="myTabs" [items]="myItems">
</ribbon-bar>-->
<div class="container">
  <nav>
    <a routerLink="/allphrases">All Phrases</a>|
    <a routerLink="/sentence">Sentence</a>|
    <a routerLink="/phrase/0">Phrase</a>|
    <a routerLink="/simplevalidation">simplevalidation</a>|
    <a routerLink="/messagesvalidation">messagesvalidation</a>
  </nav>
  <div class="header">
    <h3 class="text-muted">{{title}}</h3>
  </div>
  <div class="jumbotron">
    <router-outlet></router-outlet>
  </div>
  <div class="footer">
    <p>&copy; Feifei 2016</p>
  </div>
</div>
<!-- /container -->

// client_react/src/app.js
import React from 'react';
import { Link, Route, Switch } from 'react-router-dom';
import { Phrase } from './phrase';
import { Sentence } from './sentence';
import { WordList } from './wordList';

const Home = () => <div>Home</div>;

export class App extends React.Component {
    render() {
        return <div className="container">
            <nav>
                <Link to="/allphrases">All Phrases</Link>|
                <Link to="/sentence">Sentence</Link>|
                <Link to="/phrase/0">Phrase</Link>|
            </nav>
            <div className="header">
                <h3 className="text-muted">My Words</h3>
            </div>
            <div className="jumbotron">
                <Switch>
                    <Route exact path='/' component={Home} />
                    <Route path='/allphrases' component={WordList} />
                    <Route path='/sentence' component={Sentence} />
                    <Route path='/phrase/0' component={Phrase} />
                </Switch>
            </div>
            <div className="footer">
                <p>&copy; Feifei 2016</p>
            </div>
        </div>
    }
}
