// client_react/src/phrase.js
import React from 'react';
import { observer } from 'mobx-react';

@observer(['phraseStore'])
export class Phrase extends React.Component {
    audio;

    constructor(props) {
        super(props);
        this.audio = new Audio();
        this.play = this.play.bind(this);
        this.onKey = this.onKey.bind(this);
    }

    play(e, phrase) {
        e.preventDefault;
        this.audio.onended = () => {
            this.audio.onended = null;
            if (phrase.sentences && phrase.sentences.length) {
                this.audio.src = 'http://dict.youdao.com/dictvoice?audio=' + phrase.sentences[0] + '&type=2';
                this.audio.play();
            }
        };
        this.audio.pause();
        this.audio.src = 'http://dict.youdao.com/dictvoice?audio=' + phrase.phrase + '&type=2';
        this.audio.play();
    }

    onKey(e) {

    }

    componentDidMount() {
        this.props.phraseStore.init(this.props.match.params.id);
    }

    render() {
        const store = this.props.phraseStore;
        const phrase = store.phrase;
        if (phrase) {
            let sentenceList;
            if (phrase.sentences && phrase.sentences.length) {
                sentenceList = phrase.sentences.map((s, i) => <li key={i} className="list-group-item">
                    {s}
                </li>);
            }

            return <div >
                <h2 className="text-center">{phrase.phrase}</h2>
                <h2 className="text-center" style={{ color: 'gray', dispaly: 'inline-block' }}>{phrase.phonetic}
                    <a href="#" onClick={(e) => this.play(e, phrase)}>
                        <span className="glyphicon glyphicon-volume-up"></span>
                    </a>
                </h2>
                <br />
                {store.showMeaning &&
                    <div>
                        {phrase.meaning}
                    </div>}
                {sentenceList &&
                    <ul className="list-group">
                        {sentenceList}
                    </ul >
                }
                <div className="text-center">
                    {store.showNext || <div>
                        <button className="btn btn-info" onClick={store.remember}>I remember</button>
                        <button className="btn btn-info" onClick={store.forget} > I forget</button >
                    </div >}
                    <h2 style={{ dispaly: 'inline-block' }}>
                        {store.showNext &&
                            <a href="#" onClick={store.next}>
                                <span className="glyphicon glyphicon-arrow-right"></span>
                            </a>
                        }
                    </h2 >
                </div >

                <br />
                <br />
                {store.showAddExample &&
                    <div>
                        <textarea value={store.example} onChange={store.exampleChange}></textarea >
                        <br />
                        <button className="btn btn-info" onClick={store.addExample}>add example to this phrase</button>
                    </div>
                }
            </div >
        }
        else {
            return <div>loading phrase...</div>
        }
    }
}

// client/app/phrase.component.ts
import { Component, OnInit } from '@angular/core';
import { PhraseService } from './phrase.service';
import { Router, ActivatedRoute, Params } from '@angular/router';
import 'rxjs/add/operator/switchMap';

@Component({
    selector: 'phrase',
    templateUrl: 'phrase.component.html'
})
export class PhraseComponent {
    phrase: any;
    title: string;
    audio: any;
    showMeaning: boolean;
    keycode: any;
    example: string;
    showNext: boolean;
    showAddExample: boolean;

    constructor(private phraseService: PhraseService,
        private route: ActivatedRoute,
        private router: Router) {
        this.title = '';
        this.phrase = {};
        this.audio = new Audio();
        this.example = '';
    }

    ngOnInit() {
        let id = this.route.params.subscribe((params) => {
            this.showMeaning = false;
            this.showAddExample = false;
            this.showNext = false;
            this.phraseService.getPhrase(params['id']).then(data => {
                this.phrase = data;
                this.play();
            });
        });
    }

    private play() {
        this.audio.onended = () => {
            this.audio.onended = null;
            if (this.phrase.sentences && this.phrase.sentences.length) {
                this.audio.src = 'http://dict.youdao.com/dictvoice?audio=' + this.phrase.sentences[0] + '&type=2';
                this.audio.play();
            }
        };
        let phrase = this.phrase.phrase;
        this.audio.pause();
        this.audio.src = 'http://dict.youdao.com/dictvoice?audio=' + phrase + '&type=2';
        this.audio.play();
    }

    onKey(event: any) {
        if (event.code === 'ArrowRight') {
            this.next();
        }
        else if (event.code === 'KeyP') {
            this.play();
        }
    }

    remember() {
        this.next();
    }

    next() {
        this.ngOnInit();
    }

    addExample() {
        this.phraseService.insertExample(this.phrase.phrase_id, this.example).then(data => {
            console.log(data);
        })
    }
}
<div class="row">
  <div class="col">
    <div ngbDropdown class="d-inline-block">
      <button class="btn btn-outline-primary" id="dropdownMenu1" ngbDropdownToggle>Toggle dropdown</button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <button class="dropdown-item">Action - 1</button>
        <button class="dropdown-item">Another Action</button>
        <button class="dropdown-item">Something else is here</button>
      </div>
    </div>
  </div>
</div>

<div (keyup)="onKey($event)">
	<h2 class="text-center">{{phrase.phrase}}</h2>
	<h2 class="text-center" style="color:gray;dispaly:inline-block;">{{phrase.phonetic}}
		<a href="#" onclick='return false;' (click)="play();">
			<span class="glyphicon glyphicon-volume-up"></span>
		</a>
	</h2>
	<br>
	<div [hidden]="!showMeaning">
		{{phrase.meaning}}
	</div>
	<ul class="list-group" [hidden]="!showMeaning">
		<li class="list-group-item" *ngFor="let sentence of this.phrase.sentences">
			{{sentence}}
		</li>
	</ul>

	<div class="text-center">
		<div [hidden]="showNext">
			<button class="btn btn-info" (click)="remember()">I remember</button>
			<button class="btn btn-info" (click)="showMeaning=!showMeaning;showNext=!showNext;">I forget</button>
		</div>
		<h2 style="dispaly:inline-block;">
			<a href="#" [hidden]="!showNext" onclick="return false;" (click)="next()">
				<span class="glyphicon glyphicon-arrow-right"></span>
			</a>
		</h2>
	</div>

	<br>
	<br>
	<div [hidden]="!showAddExample"> 
		<textarea [(ngModel)]="example"></textarea >
    <br>
    <button class="btn btn-info" (click)="addExample()">add example to this phrase</button>
	</div>
</div>
